name: Build & Publish ROS2 Images
on:
  push:
    branches: [ master ]
    paths:
    - 'ros2/**'
    - '.github/workflows/ros2_images.yaml'
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ros2
    steps:
      - uses: actions/checkout@master
      - name: Build Images
        run:  make ros2-base
      - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        run: make push