name: ROS2 Base Image

on:
  push:
    branches: [ master ]
    paths:
    - 'ros2-base/**'
    - '.github/workflows/ros2-base.yaml'

jobs:
  build:
    runs-on: Default
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ros2-base/Dockerfile --tag ros2-base:$(date +%s)
