name: Build & Publish ROS2 Images
on:
  push:
    branches: [ master ]
    paths:
    - 'ros2/**'
    - '.github/workflows/ros2_images.yaml'
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../ros2
    steps:
      - name: Build Images
        run:  make ros2-base