name: Build Slam ROS image
on:
  push:
    branches: [ master ]
    paths:
    - 'slam/**'
    - '.github/workflows/slam_image.yaml'
jobs:
  francor-ros2-images:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - uses: actions/checkout@master
      - name: Build & Push SLAM Image
        run: make slam && docker push franc0r/ros2-slam:galactic 